#!/bin/sh

# read in our hardware configs
if [ -e /var/run/breakin.dat ]
then
	. /var/run/breakin.dat
fi

# Generate the hpl config file
cat > /tmp/HPL.dat <<EOF
HPLinpack benchmark input file
Innovative Computing Laboratory, University of Tennessee
HPL.out      output file name (if any)
6            device out (6=stdout,7=stderr,file)
1            # of problems sizes (N)
`@DESTDIR@/bin/hpl_calc_n ${MEM_TOTAL}`         Ns
1            # of NBs
128    	NBs
0            PMAP process mapping (0=Row-,1=Column-major)
1            # of process grids (P x Q)
`@DESTDIR@/bin/hpl_calc_pq ${CPU_QTY}`
16.0         threshold
1            # of panel fact
2            PFACTs (0=left, 1=Crout, 2=Right)
1            # of recursive stopping criterium
4            NBMINs (>= 1)
1            # of panels in recursion
2            NDIVs
1            # of recursive panel fact.
1            RFACTs (0=left, 1=Crout, 2=Right)
1            # of broadcast
1            BCASTs (0=1rg,1=1rM,2=2rg,3=2rM,4=Lng,5=LnM)
1            # of lookahead depth
1            DEPTHs (>=0)
2            SWAP (0=bin-exch,1=long,2=mix)
64           swapping threshold
0            L1 in (0=transposed,1=no-transposed) form
0            U  in (0=transposed,1=no-transposed) form
1            Equilibration (0=no,1=yes)
8            memory alignment in double (> 0)
EOF

export OMP_PROC_BIND=TRUE
export OMP_PLACES=cores
export OMP_NUM_THREADS=`/usr/bin/lscpu | grep 'per core' | awk '{print $4}'`
export OMPI_MCA_plm_rsh_agent=/usr/bin/rsh
export OMPI_MCA_btl_vader_single_copy_mechanism=none
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

if [ -x @DESTDIR@/bin/hpl ]
then
	cd /tmp
	/usr/bin/mpirun --allow-run-as-root -np ${CPU_QTY} --oversubscribe -mca btl vader,self -stdin none @DESTDIR@/bin/hpl > /tmp/hpl.log 2>&1
else
	echo "Binary for this host is not available."
	rm -f /tmp/HPL.dat
	exit 255
fi

if [ "$?" -ne 0 ]
then
	touch /var/log/breakin.error.log
	cat /tmp/hpl.log >> /var/log/breakin.error.log
	rm -f @DESTDIR@/bin/HPL.dat /tmp/hpl.log
	sync
	echo "test failed possible memory or cpu errors" 
	exit 1
else
	GFLOPS=`grep ^WR /tmp/hpl.log | tail -1 | awk '{print $7}'`
	echo "MSG: Passed (${GFLOPS} GFLOPS)" 
	cp /tmp/hpl.log /tmp/hpl.log.previous
	rm -f /tmp/HPL.dat
	exit 0
fi

sleep 1
rm -f /tmp/HPL.dat
killall -9 @DESTDIR@/bin/hpl > /dev/null 2>&1
sleep 5

