#!/bin/sh
# read /dev/mcelog every 10 seconds 

FOUND_ERROR=0
TS=`/usr/bin/date +%s`
DATE=`expr ${TS} - 10`
DATE=`/usr/bin/date -d "@${DATE}" +'%Y-%m-%d %H:%M:%S'`

# This assumes running on Debian or some other distro that uses systemd
#
# The kernel will log events with 'mce:', the data captured by rasdaemon
# appears to get logged to the journal with 'mce_record:'
if /usr/bin/journalctl -q -a -S "${DATE}" -g '(mce: \[Hardware)|(mce_record:)' 2>/dev/null 1>&2
then
	FOUND_ERROR=1
	/usr/bin/journalctl -q -a -S "${DATE}" -g '(mce: \[Hardware)|(mce_record:)' 2>/dev/null
fi

sleep 10
exit $FOUND_ERROR 
