#!/bin/ash
# read /dev/mcelog every 10 seconds 

. /etc/library.sh

FOUND_ERROR=0

OUTPUT=`/usr/sbin/mcelog --dmi`
RETVAL=$?
if [ $RETVAL = 1 ]
then

	msg "mcelog couldn't access mce, mem, or dmi data"
	exit 255

elif [ $RETVAL = 0 ]
then
	if [ -n "${OUTPUT}" ]
	then
		FOUND_ERROR=1
		echo "${OUTPUT}"
	fi

fi
sleep 10
exit $FOUND_ERROR 
